ShopFloor.Web/Controllers/ManufacturingOrderController.cs
using ShopFloor.Entities;
using ShopFloor.Managers;
using ShopFloor.SAP.Managers;
using ShopFloor.Web.Models;
using ShopFloor.Web.Models.DataTables;
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using System.Linq;
using ShopFloor.Business;

namespace ShopFloor.Web.Controllers
{
	[Authorize]
	public class ManufacturingOrderController : BaseController
	{
		MOHeaderManager db = new MOHeaderManager();

		#region Action Result

		public ActionResult Index()
		{
			return View();
		}

		public ActionResult Create()
		{
			ViewBag.MOTypes = this.GetMOTypes();

			var mo = new EditMOHeaderModel();
			mo.MONumber = db.GetMaxIntValue(m => m.MONumber) + 1;

			return View(mo);
		}


		[HttpPost]
		public ActionResult Create(EditMOHeaderModel model)
		{
			if (ModelState.IsValid)
			{
				if (!db.IsDuplicate(m => m.MONumber == model.MONumber && m.MOTypeID == model.MOTypeID))
				{
					model.CreatedBy = db.GetUserIDByUsername(this.User.Identity.Name);
					model.CreatedOn = DateTime.Now;
					int newid = db.Create(model);

					AddMessageSuccess("Successfully created MOHeader!");
					return RedirectToAction("Edit", new { id = newid });
				}
				ModelState.AddModelError("", "Duplicate Manufcaturing Order (same Number and Type) found.");
			}
			ViewBag.MOTypes = this.GetMOTypes();
			return View(model);
		}

		public ActionResult Edit(int? id)
		{
			if (!id.HasValue)
				return RedirectToAction("Index");

			ViewBag.MOTypes = this.GetMOTypes();
			var model = db.Map(db.GetByID(id.Value), new EditMOHeaderModel());
			model.FinishedGoods = db.GetFinishedGoods(id.Value);
			model.CurrentDateTime = TempData["CurrentDateTime"] as DateTime? ?? DateTime.Now;

			if(model.DownTimeRouteID > 0)
			{
				var route = new RoutesManager().GetByID(model.DownTimeRouteID.Value);
				if(route!= null)
				{
					model.RouteDisplayName = $"{route.RouteCode} - {route.RouteDesc}";
				}
			}

			return View(model);
		}

		[HttpPost]
		public ActionResult Edit(EditMOHeaderModel model)
		{
			if (ModelState.IsValid)
			{
				var entity = db.GetByID(model.ID);
				entity.MONumber = model.MONumber;
				entity.MOTypeID = model.MOTypeID;
				entity.GangRunTag = model.GangRunTag;
				entity.ModifiedBy = db.GetUserIDByUsername(User.Identity.Name);
				entity.ModifiedOn = DateTime.Now;

				db.Save(entity);
				
				AddMessageSuccess("MO successfully saved.");

				return RedirectToAction("Edit", model.ID);
			}

			ViewBag.MOTypes = this.GetMOTypes();
			model.FinishedGoods = db.GetFinishedGoods(model.ID);
			model.CurrentDateTime = model.CurrentDateTime;
			return View(model);
		}

		public ActionResult MOClosing(int? id)
		{
			if (!id.HasValue)
				return RedirectToAction("Index");

			ViewBag.MOTypes = this.GetMOTypes();
			var model = db.Map(db.GetByID(id.Value), new EditMOHeaderModel());
			model.FinishedGoods = db.GetFinishedGoods(id.Value);
			model.CurrentDateTime = TempData["CurrentDateTime"] as DateTime? ?? DateTime.Now;
			model.IsMOClosing = true;
			return View("Edit", model);
		}

		public ActionResult CreateFinishedGood(EditMODetailFggModel model)
		{
			if (ModelState.IsValid)
			{
				// get MO header
				var moHeader = new MOHeaderManager().GetByID(model.MOHeaderID);


				// Create FGG
				int createdBy = db.GetUserIDByUsername(User.Identity.Name);
				model.CreatedBy = createdBy;
				model.CreatedOn = DateTime.Now;
				var item = new SAP.Managers.SAPItemManager().GetByItemCode(model.ItemCode);
				if (item != null)
				{
					model.ItemName = item.ItemName;
				}


				// save to database
				var dbFGG = new MODetailFGGManager();
				model.ID = dbFGG.Create(model);


				// add resources for this FGG
				var dbRSC = new MODetailRSCManager();
				if(moHeader.GangRunTag.GetValueOrDefault(false))
				{
					dbRSC.CreateFromFGGGangRun(model);
				}
				else
				{
					dbRSC.CreateFromFGG(model);
				}


				// add raw materials for this FGG
				var dbITM = new MODetailITMManager();
				dbITM.CreateFromItemCode(model.ItemCode, model.ID, createdBy);


				return MOContent(model.MOHeaderID);
			}

			return null;
		}

		public ActionResult MOContent(int id)
		{
			var mo = db.GetByID(id);
			var model = new EditMOHeaderModel();
			model = db.Map(mo, model);
			model.FinishedGoods = db.GetFinishedGoods(id);

			return PartialView("_MOContent", model);
		}

		public ActionResult DeleteFGG(int id)
		{
			//delete child records - schedule
			var dbSched = new MOResourceScheduleManager();
			dbSched.DeleteSchedByFGGID(id);

			//delete child records - RSC
			var dbFGG = new MODetailFGGManager();
			dbFGG.DeleteRSCByFGGID(id);

			//delete child records - ITM
			dbFGG.DeleteITMByFGGID(id);

			// remember MOHeaderID first
			int moHeaderID = dbFGG.GetByID(id).MOHeaderID;

			//delete FGG record
			dbFGG.Flush(); //<-- calls SaveChanges to delete child records
			dbFGG.Remove(id);

			return MOContent(moHeaderID);
		}

		[HttpPost]
		public ActionResult UpdateEstTime(MODetailRsc model)
		{
			var dbRSC = new MODetailRSCManager();
			var rsc = dbRSC.GetByID(model.ID);
			rsc.ModifiedBy = dbRSC.GetUserIDByUsername(User.Identity.Name);
			rsc.ModifiedOn = DateTime.Now;
			rsc.EstTime = model.EstTime;
			rsc.SetupTime = model.SetupTime;
			rsc.StockTime = model.StockTime;
			dbRSC.Save(rsc);

			dbRSC.UpdateMOSchedule(rsc.MODetailFgg.MOHeaderID);

			return MOContent(rsc.MODetailFgg.MOHeaderID);
		}

		public ActionResult MOByResource()
		{
			var result = db.GetMOByResource();
			var dbResources = new ResourceManager();
			ViewBag.Resources = this.CreateSelectList(dbResources.GetAll(), m => m.ID, m => string.Format("{0} | {1}", m.ResourceCode, m.ResourceDesc));
			return View();
		}

		public ActionResult DowntimeList()
		{
			return View();
		}

		public ActionResult DownTimeCreate()
		{
			var mo = new CreateDownTime();
			mo.MONumber = db.GetMaxIntValue(m => m.MONumber) + 1;
			mo.CurrentDateTime = DateTime.Now;
			mo.MOTypeID = new ShopFloorEntityManager<MOType>(m=>m.ID).QueryAll().FirstOrDefault(m=>m.MOTypeCode == ShopFloor.Constants.CONST_MOTYPES_FILLER)?.ID ?? 0;
			var dbRoutes = new RoutesManager();
			ViewBag.Routes = CreateSelectList(dbRoutes.GetDownTimeRoutes(), m => m.ID, m => $"{m.RouteCode}|{m.RouteDesc}");
			return View(mo);
		}

		[HttpPost]
		public ActionResult DownTimeCreate(CreateDownTime downTime)
		{
			if (ModelState.IsValid)
			{
				int createdBy = db.GetUserIDByUsername(User.Identity.Name);
				var dbFGG = new MODetailFGGManager();
				var dbRSC = new MODetailRSCManager();

				// create an MO
				var mo = new MOHeader();
				mo.CreatedBy = createdBy;
				mo.CreatedOn = DateTime.Now;
				mo.MOTypeID = GetFillerMOTypeID();
				mo.MONumber = downTime.MONumber;
				mo.DownTimeRouteID = downTime.RouteID;
				db.Create(mo);

				// get all item routes
				var dbItemRoutes = new ItemRouteManager();
				var itemRoutes = dbItemRoutes.GetAllByRouteID(downTime.RouteID);
				foreach(var itemRoute in itemRoutes)
				{

					// create new fgg
					var fgg = new MODetailFgg();
					fgg.ItemCode = itemRoute.ItemCode;
					fgg.ItemName = itemRoute.ItemName;
					fgg.MOHeaderID = mo.ID;
					fgg.CreatedBy = createdBy;
					fgg.CreatedOn = DateTime.Now;
					fgg.ID = dbFGG.Create(fgg);

					// add resources for this FGG
					dbRSC.CreateFromFGG(fgg);
				}

				return RedirectToAction("DownTimeEdit", new { id = mo.ID });
			}
			return View(downTime);
		}

		public ActionResult DownTimeEdit(int id)
		{
			return RedirectToAction("Edit", new { id = id });
		}



		#endregion


		#region Json Result

		public JsonResult GetNoOfClosedRSC(int id)
		{
			return Json(1, JsonRequestBehavior.AllowGet);
		}

		[HttpPost]
		public JsonResult CloseMO(int id)
		{
			db.CloseMO(id);
			return Json(true, JsonRequestBehavior.AllowGet);
		}

		public JsonResult Delete(int id)
		{
			var mo = db.GetByID(id);
			db.ArchiveMO(mo);

			db.Remove(id);

			return Json(true, JsonRequestBehavior.AllowGet);
		}


		public JsonResult ValidateFGG(string itemcode, int id)
		{
			//var routeDb = new RoutesManager();
			//routeDb.IsDuplicate(m=>m.ItemCode)

			var dbFGG = new MODetailFGGManager();
			if (dbFGG.HasDuplicateItemCode(itemcode, id))
			{
				return Json("There is already an existing item code for this MO.", JsonRequestBehavior.AllowGet);
			}

			var dbSAP = new SAPItemManager();
			if (!dbSAP.IsDuplicate(m => m.ItemCode == itemcode))
			{
				return Json("This Item Code is invalid or does not exist.", JsonRequestBehavior.AllowGet);
			}

			var dbBOM = new BOMManager();
			if (!dbBOM.IsEffective(itemcode))
			{
				return Json("The BOM Effectivity date has expired.", JsonRequestBehavior.AllowGet);
			}

			return Json(true, JsonRequestBehavior.AllowGet);
		}

		public JsonResult UpdateFGG(MODetailFgg entity)
		{

			// pull values for docEntry and lineNum
			int? docEntry = null;
			int? lineNum = null;
			var dbSOMgr = new SAPOrderManager();
			SAP.Entities.Order order = null;
			if (entity.SONo > 0)
				order = dbSOMgr.GetByDocNum(entity.SONo ?? 0);
			if (order != null && order.OrderEx != null)
			{
				docEntry = order.DocEntry;
				lineNum = order.OrderEx.LineNum;
			}



			var dbRSC = new MODetailFGGManager();
			var e = dbRSC.GetByID(entity.ID);
			e.SAPRDR1DocEntry = docEntry;
			e.SAPRDR1LineNum = lineNum;
			e.OutsTag = entity.OutsTag ?? e.OutsTag;
			e.SONo = entity.SONo;
			e.DeliveryDate = entity.DeliveryDate ?? e.DeliveryDate;
			e.ModifiedBy = db.GetUserIDByUsername(User.Identity.Name);
			e.ModifiedOn = DateTime.Now;
			dbRSC.Save(e);

			return Json(true, JsonRequestBehavior.AllowGet);
		}

		public JsonResult UpdateITM(MODetailItm entity)
		{
			var dbITM = new MODetailITMManager();
			var e = dbITM.GetByID(entity.ID);
			e.ModifiedBy = dbITM.GetUserIDByUsername(User.Identity.Name);
			e.ModifiedOn = DateTime.Now;
			e.MOQty = entity.MOQty;

			e.RMItemCode = entity.RMItemCode;
			e.RMItemName = entity.RMItemName;
			//e.IssuedQty = entity.IssuedQty; changed to readonly
			e.IssuedQty2 = entity.IssuedQty2;

ShopFloor.Web/Views/ManufacturingOrder/Create.cshtml
@model ShopFloor.Web.Models.EditMOHeaderModel
@{
    ViewBag.Title = "Create MO";
    ViewBag.ActiveMenu = "MO";
    Layout = "~/Views/Shared/_LayoutTasks.cshtml";
}

<h2>Manufacturing Order Creation</h2>
<h4>Create MO Header</h4>
<hr />

<div class="col-lg-8 col-md-9">
@using (Html.BeginForm("test"))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.MOType, htmlAttributes: new { @class = "control-label col-md-3" })
            <div class="col-md-9">
                @Html.DropDownListFor(model => model.MOTypeID, (IEnumerable<SelectListItem>)ViewBag.MOTypes, "", new { @class = "form-control", autofocus = "" })
                @Html.ValidationMessageFor(model => model.MOTypeID, "", new { @class = "text-danger" })
            </div>
        </div>


		<div class="form-group">
			@Html.LabelFor(model => model.MONumber, htmlAttributes: new { @class = "control-label col-md-3" })
			<div class="col-md-9">
				@Html.EditorFor(model => model.MONumber, new { htmlAttributes = new { @class = "form-control" } })
				@Html.ValidationMessageFor(model => model.MONumber, "", new { @class = "text-danger" })
			</div>
		</div>

		<div class="form-group">
			<label class="control-label col-md-3" for="MOInstructions">Special Instructions</label>
			<div class="col-md-9">
				@Html.TextAreaFor(model => model.MOInstructions, new { @class = "form-control" })
				@Html.ValidationMessageFor(model => model.MOInstructions, "", new { @class = "text-danger" })
			</div>
		</div>

        <div class="form-group">
            @Html.LabelFor(model => model.GangRunTag, htmlAttributes: new { @class = "control-label col-md-3" })
            <div class="col-md-9">
                <div class="checkbox">
                    @Html.EditorFor(model => model.GangRunTag)
                    @Html.ValidationMessageFor(model => model.GangRunTag, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        @*@Html.HiddenFor(m => m.ID)
        @Html.HiddenFor(m => m.MOPriority)
        @Html.HiddenFor(m => m.MOClosedTag)
        @Html.HiddenFor(m => m.CreatedBy)
        @Html.HiddenFor(m => m.CreatedOn)
        @Html.HiddenFor(m => m.ModifiedBy)
        @Html.HiddenFor(m => m.ModifiedOn)*@


        <div class="form-group">
            <div class="col-md-offset-3 col-md-9">
                <button id="btn-create" type="submit" class="btn btn-success"><span class="glyphicon glyphicon-arrow-right"></span>&nbsp;Next</button>
            </div>
        </div>
    </div>
}

<p>
    @Html.ActionLink("Search MO", "Index")
</p>

</div>

@section Scripts{

    
    <script>

        $(function () {
            $('#btn-create').click(function () {
                if (!confirm('This will create a blank MO record. Are you sure you want to continue?')) {
                    return false;
                }
            })


            $('#MOTypeID').change(function (s) {

                // get next series
                var url = '@Response.ApplyAppPathModifier("/ManufacturingOrder/GetNextSeriesValue/?moTypeId=")' + $(this).val();
                $.get(url, function (value) {
                    $('#MONumber').val(value);
                })
                
            });
        })

    </script>

}

ShopFloor.Web/Views/ManufacturingOrder/DowntimeList.cshtml
@model IEnumerable<ShopFloor.Entities.MOHeader>


@{
    ViewBag.Title = "Downtime";
}

<h2>DownTime</h2>

<div class="row">
    <div class="col-md-7 col-sm-7 col-xs-7">
	    @using(Html.BeginForm("Form1")){
        <div class="input-group">
			<input type="text" class="form-control" placeholder="search" name="SearchString">
            <span class="input-group-btn">
                <button type="submit" class="btn btn-primary"><span class="glyphicon glyphicon-search"></span></button>
            </span>
        </div>
		}
    </div>
    <div class="col-md-5 col-sm-5 col-xs-5">
        <a href="@Url.Action("DownTimeCreate")" class="btn btn-success pull-right"><span class="glyphicon glyphicon-plus"></span>&nbsp;Create New</a>
    </div>
</div>
<table class="table table-striped table-hover table-search">
	<thead>
    <tr>
        <th>
            @Html.DisplayNameFor(m=>m.MONumber)
        </th>
		<th>
			@Html.DisplayNameFor(m => m.MOType.MOTypeName)
		</th>
        <th>
            @Html.DisplayNameFor(m=>m.MOPriority)
        </th>
        <th></th>
    </tr>
	</thead>
	<tbody>
	</tbody>

</table>


@section Scripts{
    <link href="~/Content/dataTables.bootstrap.css" rel="stylesheet" />
    <script src="~/Scripts/jquery.dataTables.min.js"></script>
    <script src="~/Scripts/dataTables.bootstrap.js"></script>
    <script src="~/Scripts/shopfloor.datatable.js"></script>
    <script>

        var table = {};

        $(function () {

            table = new SearchTable('', '.table-search', '#SearchString', '#btn-search-operation', undefined, editClick, deleteClick);
            table.AjaxURL = '@Response.ApplyAppPathModifier(Url.Action("GetDownTimeList", "ManufacturingOrder"))';
        	table.addDataTableColumn('MONumber', true, true);
        	table.addDataTableColumn('MOType.MOTypeName', true, true);
			table.addDataTableColumn('MOPriority', true, true);
			table.showActionButtons = true;
            table.showSelectButton = false;
            table.initialize();


            $('.btn-delete-row').click(function () {

            });
        });

        var editClick = function (id) {
            var url = '@Url.Action("Edit", new { id = "[recordid]" })';
            url = url.replace('[recordid]', id);
            location.replace(url);
        };

        var deleteClick = function (id) {
            var url = '@Url.Action("Delete", new { id = "[recordid]" })';
            url = url.replace('[recordid]', id);
            $.get(url, function () {
                table.reload();
                toastr['success']('Record successfully deleted.');
            })
            .fail(function () {
                toastr['error']('Operation is in use. Unable to delete.');
            });
        };

    </script>
}

ShopFloor.Web/Views/ManufacturingOrder/Index.cshtml
@model ViewMOHeaderModel
@{
    ViewBag.Title = "MO";
    ViewBag.ActiveMenu = "SearchMO";
    Layout = "~/Views/Shared/_LayoutTasks.cshtml";
}

<h2>Search MOs</h2>

<div class="row">
    <div class="col-md-7 col-sm-12 col-xs-12">
        <div class="input-group">
            <input type="text" class="form-control txt-table-search" placeholder="enter MO or item details" name="SearchString" autofocus>
            <span class="input-group-btn">
                <button type="submit" class="btn btn-primary btn-search btn-table-search"><span class="glyphicon glyphicon-search"></span></button>
                <a href="@Url.Action("MOByResource", "ManufacturingOrder")" class="btn btn-default">OR Search By Resource</a>
            </span>
        </div>
    </div>
    <div class="col-md-5 col-sm-12 col-xs-12">
        
        <a href="@Url.Action("Create")" class="btn btn-success pull-right"><span class="glyphicon glyphicon-plus"></span>&nbsp;Create New</a>
        
    </div>
</div>

<div class="scollable-table-container">
    <table class="table table-striped table-search" id="table-search-route">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.MONumber)
                </th>
                <th class="">
                    @Html.DisplayNameFor(model => model.MOType)
                </th>
                <th class="">
                    @Html.DisplayNameFor(model => model.MOPriority)
                </th>
                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody></tbody>

    </table>
</div>


@section Scripts{

    <style>
        .scrollable-table-container table {
            min-width:555px;
        }
    </style>

    <link href="~/Content/dataTables.bootstrap.css" rel="stylesheet" />
    <script src="~/Scripts/jquery.dataTables.min.js"></script>
    <script src="~/Scripts/dataTables.bootstrap.js"></script>
    <script src="~/Scripts/shopfloor.datatable.js"></script>
    <script>

        btnDeleteRow_Click = function (id) {
            $.get('@Response.ApplyAppPathModifier("/ManufacturingOrder/Delete/")' + id, function () {
                t1.reload();
                toastr['success']('Record deleted.');
            })
            .fail(function () {
                alert('unable to delete record. a Work in Process has been initialized for this MO.');
            });
        }

        btnEditRow_Click = function (id) {
            location.href = '@Response.ApplyAppPathModifier("/ManufacturingOrder/Edit/")' + id
        }

        var t1 = new SearchTable('mo', '.table-search', '.txt-table-search', '.btn-table-search', undefined, btnEditRow_Click, btnDeleteRow_Click);
        t1.AjaxURL = '@Response.ApplyAppPathModifier("/search/search?table=mo")';
        t1.addDataTableColumn('MONumber', true, true);
        t1.addDataTableColumn('MOType.MOTypeName', true, true);
        t1.addDataTableColumn('MOPriority', true, true);
        t1.addDataTableColumnCustom(function (data) { var url = '@Response.ApplyAppPathModifier("/datacapture/index/")' + data.ID; return "<a href=" + url + " class='btn btn-info btn-xs'><i class='glyphicon glyphicon-flag'></i> Work in Process</a>"; }, false, false, true);
        t1.showActionButtons = true;
        t1.showSelectButton = false;
        t1.initialize();

        $(function () {
            $('#btn-add-fg').click(function () {
                $('#modal-add-fg').modal('show');
            });
        });


    </script>
}

ShopFloor.Web/Views/ManufacturingOrder/MOByResource.cshtml
@{
    ViewBag.Title = "MO By Resource";
    ViewBag.ActiveMenu = "MOByResource";
    Layout = "~/Views/Shared/_LayoutTasks.cshtml";
}

<h2>Resources Schedule</h2>
<h3>Search MO By Resource</h3>

<div class="row">
    <div class="col-xs-9 col-sm-9 col-md-6 col-lg-6">
        @Html.DropDownList("ResourceID", (IEnumerable<SelectListItem>) ViewBag.Resources, "", new { @class = "form-control" })
    </div>
    <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3">
        <a href="@Url.Action("Index", "ManufacturingOrder")" class="btn btn-default"><i class="fa fa-search"></i> Back to Normal Search</a>
    </div>

</div>
<hr />
<div class="row">
    <div class="col-lg-12">
    <div class="panel panel-primary">
        <div class="panel-heading bolder">Search Results</div>
        <div class="panel-body">
            <table class="table table-condensed table-search">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Resource ID</th>
                        <th>Priority</th>
                        <th>MO Number</th>
                        <th>FG Code</th>
                        <th>FG Name</th>
                        <th>Start Date</th>
                        <th>Start Time</th>
                        <th>Est. Run Time</th>
                        <th>End Date</th>
                        <th>End Time</th>
                        <th>Delivery Date</th>
                        <th>Scheduled</th>
                        <th>Status</th>
                    </tr>
                </thead>
            </table>
        </div>
    </div>
    </div>
</div>


@section Scripts{
    <link href="~/Content/dataTables.bootstrap.css" rel="stylesheet"/>
    <link href="~/Content/css/select2.css" rel="stylesheet"/>
    <link href="~/Content/select2-bootstrap.css" rel="stylesheet"/>
    <script src="~/Scripts/jquery.dataTables.min.js"></script>
    <script src="~/Scripts/dataTables.bootstrap.js"></script>
    <script src="~/Scripts/shopfloor.datatable.js"></script>
    <script src="~/Scripts/select2.min.js"></script>
    <script>
        $(function() {

            var table = new SearchTable('',
                '.table-search',
                '',
                '#btn-table-search',
                undefined,
                btnEditRow_Click,
                btnDeleteRow_Click);
            table.addDataTableColumn('ID', false, false, false);
            table.addDataTableColumn('ResourceID', false, true, false);
            table.addDataTableColumn('MOPriority', true, false);
            table.addDataTableColumn('MONumber', false, false);
            table.addDataTableColumn('FGCode', false, false);
            table.addDataTableColumn('FGName', true, true);
            table.addDataTableColumn('DisplayStartDate', false, false);
            table.addDataTableColumn('DisplayStartTime', false, false);
            table.addDataTableColumn('DisplayEstRunTime', false, false);
            table.addDataTableColumn('DisplayEndDate', false, false);
            table.addDataTableColumn('DisplayEndTime', false, false);
            table.addDataTableColumn('DisplayDeliveryDate', false, false);
            table.addDataTableColumn('IsScheduled', false, false);
            table.addDataTableColumn('Status', false, false);
            table.showActionButtons = false;
            table.showSelectButton = false;
            table.ServerSide = false;
            table.AjaxURL = '@Response.ApplyAppPathModifier("/manufacturingorder/GetMOByResource/")';
            table.ZeroRecords = "No records found for selected Resource.";
            table.initialize();

            $('#ResourceID')
                .change(function() {
                    var selectedItem = $("#ResourceID option:selected");
                    var value = selectedItem.val();
                    if (!value)
                        value = 'CBA2DD3A-4C11-426B-83C2-14AA5AC938C7'; // unique value. just to empty search result.


                    // build search arguments
                    var args = [];
                    args.push({
                        "colindex": 1, // ResourceID
                        "value": value
                    });
                    table.filter(args);


                });

            //$('#ResourceID').change();
            $('#ResourceID')
                .select2({
                    placeholder: "choose a resource to filter"
                })
                .val("")
                .trigger("change");
        });

        var btnDeleteRow_Click = function(id) {
            alert('delete');
            //$.get('/bom/delete/' + id, function () {
            //}, 'json')
            //.fail(function (data) {
            //    toastr['error']('Error when trying to delete route id=' + id + '');
            //});
        }

        var btnEditRow_Click = function(id) {
            location.href = '@Response.ApplyAppPathModifier("/manufacturingorder/edit/")' + id
        }
    </script>
}