ShopFloor.Web/Controllers/DefaultController.cs
using ShopFloor.Managers;
using ShopFloor.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ShopFloor.Web.Controllers
{
    [Authorize]
    public class DefaultController : BaseController
    {
        // GET: Default
        public ActionResult Index()
        {
            // determine user role
            //var mgr = new UsersManager();
            //var user = mgr.GetByUsername(this.User.Identity.Name);
            ////if (user.UserUserClasses.UserClasses.Any(m=>m.UClassCode == "AD"))
            //if(User.IsInRole("AD"))
            //{
            //    HomeAdminModel model = new HomeAdminModel();
            //    model.Registrations = mgr.GetUserRegistrations();
            //    return View("AdminPage", model);
            //}

            return View("AdminPage");
        }

        public ActionResult UnderConstruction()
        {
            return View();
        }

        [Authorize(Roles = "AD,SU")]
        public ActionResult AdminPage()
        {
            return View();
        }

        public ActionResult QALinks()
        {
            return View();
        }

        [AllowAnonymous]
        public ActionResult About()
        {
            return View();
        }
}
}

ShopFloor.Web/Controllers/UsersController.cs
using ShopFloor.Entities;
using ShopFloor.Managers;
using ShopFloor.Web.Models;
using System;
using System.Net;
using System.Web.Mvc;

namespace ShopFloor.Web.Controllers
{
    [Authorize]
    public class UsersController : BaseController
    {
        UsersManager db = new UsersManager();

        // GET: Users
        public ActionResult Index()
        {
            return View();
        }


        // GET: Users/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.GetByID(id.Value);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // GET: Users/Create
        public ActionResult Create()
        {
            var model = new EditUserModel();
            PopulateDropDown();
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(EditUserModel user)
        {
            if (ModelState.IsValid && !IsDuplicate(user))
            {
				// users entered this way are automatically verified by current user
				var entity = new User();
				entity.UserID = user.UserID;
				entity.EmpID = user.EmpID;
				entity.UserName = user.UserName;

				entity.IsVerified = true;
				entity.VerifiedOn = DateTime.Now;
                var verifiedby = db.GetByUsername(this.User.Identity.Name);
				entity.VerifiedBy = verifiedby.ID;
				entity.UserPW = db.HashText(user.UserPW);
				entity.ChangePassword = user.ChangePassword;

                db.Create(entity);

                // create and assign user class
                var dbUC = new UserClassManager();
                dbUC.ChangeUserClassFor(user.UserName, user.UserClassID, User.Identity.Name);

                return RedirectToAction("Index");
            }

            PopulateDropDown();
            return View(user);
        }

        // GET: Users/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var user = db.GetByID(id.Value);
            if (user == null)
            {
                return HttpNotFound();
            }

            EditUserModel model = new EditUserModel();
            db.Map(user, model);

			model.UserClassID = db.GetUserClass(model.ID)?.ID ?? 0;

            PopulateDropDown();
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(EditUserModel model)
        {
            if (ModelState.IsValid && !IsDuplicate(model))
            {
				var entity = db.GetByID(model.ID);
				entity.UserName = model.UserName;
				entity.UserID = model.UserID;
				entity.EmpID = model.EmpID;

                if (model.UserPW != entity.UserPW)
                    entity.UserPW = db.HashText(model.UserPW);
				entity.ModifiedBy = db.GetUserIDByUsername(this.User.Identity.Name);
				entity.ModifiedOn = DateTime.Now;
				entity.ChangePassword = model.ChangePassword;

                db.Save(entity);

				var dbUC = new UserClassManager();
				dbUC.ChangeUserClassFor(model.UserName, model.UserClassID, User.Identity.Name);

				AddMessageSuccess("User successfully saved.");
                return RedirectToAction("Index");
            }

            PopulateDropDown();
            return View(model);
        }

        public JsonResult DeleteRecord(int id)
        {
            db.Remove(id);
            return Json(true, JsonRequestBehavior.AllowGet);
        }

        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);
        }

        public ActionResult UserRegistrations()
        {
            return View(new UsersManager().GetUserRegistrations());
        }

        public ActionResult GrantAccess(int id)
        {
            var mgr = new UsersManager();
            var user = mgr.GetByID(id);
            if (user.IsVerified.HasValue && !user.IsVerified.Value)
            {
                mgr.GrantAccess(id, this.User.Identity.Name);
                return View(user);
            }

            return View("AlreadyGranted", user);
        }

        private void PopulateDropDown()
        {
            var dbUC = new UserClassManager();
            ViewBag.UserClasses = this.CreateSelectList(dbUC.GetAll(), m => m.ID, m => m.UClassCode + " - " + m.UClassDesc);
        }

		public ActionResult IsValidUser(EditUserModel model)
		{
			if (IsDuplicate(model))
			{
				return Json("This username is already taken.", JsonRequestBehavior.AllowGet);
			}

			return Json(true, JsonRequestBehavior.AllowGet);
		}

		private bool IsDuplicate(EditUserModel model)
		{
			var isDuplicate = db.IsDuplicate(m => m.UserName == model.UserName && m.ID != model.ID);
			return isDuplicate;
		}
    }
}

ShopFloor.Web/Views/Default/About.cshtml
@{
    ViewBag.Title = "About";
}

<h2>About MICS</h2>

<p>
    @{ 
        var version = typeof(ShopFloor.Web.MvcApplication).Assembly.GetName().Version;
    }
    Web Build version @version
</p>

<p>
    @{ 
        var version2 = typeof(ShopFloor.Business.RegularMOCalculator).Assembly.GetName().Version;
    }
    Core Build version @version2
</p>

ShopFloor.Web/Views/Default/AdminPage.cshtml
@{
    ViewBag.Title = "Home Page";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@section Scripts{
    <style>
        .admin-box-item {
            /*width:350px;*/
            /*border: 1px solid black;*/
            padding: 5px 5px 5px 5px;
            margin: 7px;
            color: black;
        }
        .admin-box-item a {
            color: black;
        }

        .admin-box-item:hover {
            color: #fff;
            background-color: #1a242f;
        }

        .admin-box-item a:hover {
            color: white;
        }

    </style>
}

<h1>Tasks</h1>

<div class="text-center">
    <div class="row">

        <div class="col-md-12">

            <div class="col-lg-2 col-md-2 col-sm-3 col-xs-5 admin-box-item">
                <a href='@Url.Action("Index", "Users")'>
                    <p>
                        <i class="fa fa-5x fa-user"></i>
                    </p>
                    <p>Users</p>
                </a>
            </div>

            <div class="col-lg-2 col-md-2 col-sm-3 col-xs-5 admin-box-item">
                <a href='@Url.Action("Index", "Routes")'>
                    <p>
                        <i class="fa fa-5x fa-code-fork"></i>
                    </p>
                    <p>Routes</p>
                </a>
            </div>


            <div class="col-lg-2 col-md-2 col-sm-3 col-xs-5 admin-box-item">
                <a href='@Url.Action("Index", "Operations")'>
                    <p>
                        <i class="fa fa-5x fa-truck"></i>
                    </p>
                    <p>Operations</p>
                </a>
            </div>

            <div class="col-lg-2 col-md-2 col-sm-3 col-xs-5 admin-box-item">
                <a href='@Url.Action("Index", "Resources")'>
                    <p>
                        <i class="fa fa-5x fa-laptop"></i>
                    </p>
                    <p>Resources</p>
                </a>
            </div>

            <div class="col-lg-2 col-md-2 col-sm-3 col-xs-5 admin-box-item">
                <a href='@Url.Action("Index", "ActivityTypes")'>
                    <p>
                        <i class="fa fa-5x fa-calendar-check-o"></i>
                    </p>
                    <p>Activity</p>
                </a>
            </div>

            <div class="col-lg-2 col-md-2 col-sm-3 col-xs-5 admin-box-item">
                <a href='@Url.Action("Index", "AdditionalReasons")'>
                    <p>
                        <i class="fa fa-5x fa-commenting"></i>
                    </p>
                    <p>RM Reasons</p>
                </a>
            </div>

            @*<div class="col-lg-2 col-md-2 col-sm-3 col-xs-5 admin-box-item">
                <a href='@Url.Action("UnderConstruction", "Default")'>
                    <p>
                        <i class="fa fa-5x fa-file-code-o"></i>
                    </p>
                    <p>MO Type</p>
                </a>
            </div>*@

            @*<div class="col-lg-2 col-md-2 col-sm-3 col-xs-5 admin-box-item">
                <a href='@Url.Action("UnderConstruction", "Default")'>
                    <p>
                        <i class="fa fa-5x fa-book"></i>
                    </p>
                    <p>JE Acct Code</p>
                </a>
            </div>*@

            @*<div class="col-lg-2 col-md-2 col-sm-3 col-xs-5 admin-box-item">
                <a href='@Url.Action("UnderConstruction", "Default")'>
                    <p>
                        <i class="fa fa-5x fa-clock-o"></i>
                    </p>
                    <p>Valid Times</p>
                </a>
            </div>*@

			<div class="col-lg-2 col-md-2 col-sm-3 col-xs-5 admin-box-item">
				<a href='@Url.Action("Index", "RunRate")'>
					<p>
						<i class="fa fa-5x fa-hourglass-2"></i>
					</p>
					<p>Run Rate</p>
				</a>
			</div>

			<div class="col-lg-2 col-md-2 col-sm-3 col-xs-5 admin-box-item">
				<a href='@Url.Action("Index", "RunRateReason")'>
					<p>
						<i class="fa fa-5x fa-tags"></i>
					</p>
					<p>Run Rate Reasons</p>
				</a>
			</div>


            <div class="col-lg-2 col-md-2 col-sm-3 col-xs-5 admin-box-item">
                <a href='@Url.Action("QALinks", "Default")'>
                    <p>
                        <i class="fa fa-5x fa-search-plus"></i>
                    </p>
                    <p>QA</p>
                </a>
            </div>

			<div class="col-lg-2 col-md-2 col-sm-3 col-xs-5 admin-box-item">
				<a href='@Url.Action("Index", "BOM")'>
					<p>
						<i class="fa fa-5x fa-barcode"></i>
					</p>
					<p>BOM</p>
				</a>
			</div>

			<div class="col-lg-2 col-md-2 col-sm-3 col-xs-5 admin-box-item">
				<a href='@Url.Action("DowntimeList", "ManufacturingOrder")'>
					<p>
						<i class="fa fa-5x fa-toggle-down"></i>
					</p>
					<p>Downtime</p>
				</a>
			</div>

            <div class="col-lg-2 col-md-2 col-sm-3 col-xs-5 admin-box-item">
                <a href='@Url.Action("Index", "Processing")'>
                    <p>
                        <i class="fa fa-5x fa-spinner"></i>
                    </p>
                    <p>JE Processing</p>
                </a>
            </div>

        </div>
    </div>
</div>




   

ShopFloor.Web/Views/Default/HomeAdmin.cshtml
@model ShopFloor.Web.Models.HomeAdminModel
@{
    ViewBag.Title = "Admin Home";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<h2>Welcome</h2>
<hr />

<div class="row">

    <div class="col-lg-12">
        <ul>
            <li>No Tasks</li>
            <li>No Reminders</li>
        </ul>
    </div>

    @if (Model.Registrations.Count > 0)
    {
        @Html.Partial("~/Views/Account/_ViewRegistrationPartial.cshtml", Model.Registrations)
    }

</div>


@section LeftPane
{
    <div class="panel panel-default">
    <div class="panel-heading bold">Admin Home</div>
    <div class="list-group">
        @Html.ActionLink("Users", "Index", "Users", null, new { @class = "list-group-item" })
        @Html.ActionLink("User Registrations", "UserRegistrations", "Users", null, new { @class = "list-group-item" })
    </div>
    </div>
}

ShopFloor.Web/Views/Default/Index.cshtml
@{
    ViewBag.Title = "Home";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Welcome</h2>
<hr />

<div class="row">

    <div class="col-lg-12">
        <ul>
            <li>No Tasks</li>
            <li>No Reminders</li>
        </ul>
    </div>

</div>

@section LeftPane
{
    <p class="lead">Basic User Home</p>
    <div class="list-group">
        @Html.ActionLink("Change Password", "UnderConstruction", null, new { @class = "list-group-item" })
    </div>
}

ShopFloor.Web/Views/Default/QALinks.cshtml
@{
    ViewBag.Title = "QA Links";
    Layout = "~/Views/Shared/_LayoutQA.cshtml";
}

<h2>QA Links</h2>
<h3 class="hidden-sm hidden-xs"><i class="fa fa-arrow-left"></i> Please choose a link</h3>

ShopFloor.Web/Views/Default/UnderConstruction.cshtml
@{
    ViewBag.Title = "Under Construction. Sorry.";
}

<div class="jumbotron">
    <h1>Under Construction</h1>
    <h2>This feature will be available in Phase 2</h2>
    @Html.ActionLink("Return Home", "Index", "Default", null, new { @class="btn btn-success btn-lg" })
</div>