ShopFloor.Web/Controllers/DataCaptureController.cs
using ShopFloor.Entities;
using ShopFloor.Managers;
using ShopFloor.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace ShopFloor.Web.Controllers
{
	[Authorize]
	public class DataCaptureController : BaseController
	{
		private DataCaptureManager db = new DataCaptureManager();

		public ActionResult Index(int? id) //id == MOHeaderID
		{
			if (id == null)
			{
				return RedirectToAction("Index", "ManufacturingOrder");
			}

			PopulateDropDowns(id.Value);

			// get list of data capture
			var model = db.Map(new MOHeaderManager().GetByID(id.Value), new EditMOHeaderModel());


			return View(model);
		}

		public ActionResult Edit(int id)
		{
			// get list of data capture
			var model = db.Map(db.GetByID(id), new EditShopFloorDataCaptureModel());

			PopulateDropDowns(id);
			return View(model);
		}

		public JsonResult GetFGGJSONList(int moHeaderId)
		{
			var fggs = new MODetailFGGManager().GetByMOHeaderID(moHeaderId);

			var list = fggs.Select(fgg => new ViewDataCaptureFGG
			{
				ItemCode = fgg.ItemCode,
				ItemDescription = fgg.ItemName,
				DeliveryDate = fgg.DeliveryDate,
				MODetailFGGID = fgg.ID,
				MOQuantity = (int)(fgg.BatchQty ?? 0),
				Process = false
			}).ToList();

			return Json(list, JsonRequestBehavior.AllowGet);
		}

		public JsonResult GetDataCapture(int id)
		{
			var result = db.GetByID(id);

			var addlRM = db.GetAddlRawMaterials(id).FirstOrDefault() ?? new ShopFloorAddl();

            var rsc = db.GetMODetailRSC(result.MODetailRSCID);
			var schedStart = rsc?.FromDate ?? result.RscStartDate; // just in case resource was closed/archived
			var schedEnd = rsc?.ToDate ?? result.RscEndDate;       // get from dbo.ShopFloor.RscDATES values

			var model = new
			{
				ID = result.ID,
				Status = result.Status,
				StartDate = result.DisplayStartDate,
				EndDate = result.DisplayEndDate,
				ElapsedTime = result.DisplayElapsedTime,
				MissingScheduleDates = (result.RscStartDate == null || result.RscEndDate == null),
				ScheduleStartDate = schedStart.GetValueOrDefault(DateTime.MaxValue).ToString(ShopFloor.Constants.CONST_FORMAT_DATETIME),
				ScheduleEndDate = schedEnd.GetValueOrDefault(DateTime.MaxValue).ToString(ShopFloor.Constants.CONST_FORMAT_DATETIME),
				ScheduleElapsedTime = (schedEnd.GetValueOrDefault(DateTime.MaxValue) - schedStart.GetValueOrDefault(DateTime.MinValue)).ToString(@"hh\:mm\:ss"),
				Good = result.Good,
				NoOfOuts = result.NoOfOuts,
				SubResourceID = result.SubResourceID,
				RunRateReasonID = result.RunRateReasonID,
				ActivityType = new ActivityType
				{
					ID = result.ActivityTypeID.Value,
					ActivityCode = result.ActivityType.ActivityCode,
					ActivityName = result.ActivityType.ActivityName,
				},
				ShopFloorAddl = new ShopFloorAddl
				{
					ID = addlRM.ID,
					AdditionalReasonID = addlRM.AdditionalReasonID,
					AddlQty = addlRM.AddlQty,
					ShopFloorID = addlRM.ShopFloorID,
					RMItemCode = addlRM.RMItemCode,
				}

			};

			return Json(model, JsonRequestBehavior.AllowGet);
		}

		[HttpPost]
		public JsonResult GetResourcesForFGGs(int[] fggIDs)
		{
			if (fggIDs == null) return null;

			var resources = new MODetailRSCManager().GetAllByFGGIDs(fggIDs);
            var result = (from r in resources
                          where (r.ClosedTag ?? false) == false
                          select new
                          {
                              ResourceCode = r.ResourceCode,
                              ResourceDesc = r.ResourceDesc,
                              MOHeaderID = r.MODetailFgg.MOHeaderID,
                              Sequence = r.Sequence
                          })
						  .Distinct()
						  .OrderBy(m => m.Sequence);
			return Json(result, JsonRequestBehavior.AllowGet);
		}

		public JsonResult GetMODetailRSC(string resourceCode, int fggId)
		{
			var dbRSC = new MODetailRSCManager();
			var ret = dbRSC.QueryAll()
				.FirstOrDefault(m => m.ResourceCode == resourceCode && m.MODetailFGGID == fggId);
			var json = new
			{
				ScheduleStartDate = ret.StartDate.ToString(ShopFloor.Constants.CONST_FORMAT_DATETIME),
				ScheduleEndDate = ret.EndDate.ToString(ShopFloor.Constants.CONST_FORMAT_DATETIME),
				ScheduleElapsedTime = (ret.EndDate - ret.StartDate).ToString(@"hh\:mm\:ss"),
				ID = ret.ID
			};
			return Json(json, JsonRequestBehavior.AllowGet);
		}

		public JsonResult IsOnStreamIsNull(string resourceCode, int fggID)
		{
			var dbRSC = new MODetailRSCManager();
			var hasNullOnStreamTag = dbRSC.QueryAll()
				.Any(m => 
					m.ResourceCode == resourceCode 
					&& m.MODetailFGGID == fggID 
					&& m.OnStreamTag == null);
			return Json(hasNullOnStreamTag, JsonRequestBehavior.AllowGet);
		}

		[HttpPost]
		public JsonResult StartResource(string resourceCode, int[] fggIDs, ActivityType activity)
		{
			var d = DateTime.Now;
			var userId = db.GetUserIDByUsername(User.Identity.Name);
			var dataRetVal = new List<ShopFloorDataCapture>();
			var dbFGG = new MODetailFGGManager();
			var dbRSC = new MODetailRSCManager();
			var dbQAP = new QAParamResourceManager();
			var resources = dbRSC.GetAllByFGGIDs(fggIDs);
			var qaPars = dbQAP.GetAllByResourceCode(resourceCode);
			var newShopFloorId = 0;
			foreach (var rsc in resources)
			{
				if(rsc.ResourceCode==resourceCode)
				{
					// create ShopFloor record
					var entity = new ShopFloorDataCapture();
					entity.BatchPrcnt = (int)(rsc.BatchPercent ?? 0);
					entity.MODetailRSCID = rsc.ID;
					entity.ActivityTypeID = activity.ID;

					entity.StartDate = d;
					entity.CreatedBy = userId;
					entity.CreatedOn = d;
					entity.UserID = userId;
					entity.RscStartDate = rsc.StartDate;
					entity.RscEndDate = rsc.EndDate;
                    entity.ResourceCode = rsc.ResourceCode;
                    entity.ResourceDesc = rsc.ResourceDesc;
                    entity.MOHeaderID = rsc.MODetailFgg.MOHeaderID;
                    entity.MONumber = rsc.MODetailFgg.MOHeader.MONumber;
                    entity.MODetailFGGID = rsc.MODetailFGGID;
                    entity.ItemCode = rsc.MODetailFgg.ItemCode;
                    entity.ItemName = rsc.MODetailFgg.ItemName;
					newShopFloorId = db.Create(entity);

					// save OnStream
					rsc.OnStreamTag = true;
					rsc.ModifiedOn = d;
					rsc.ModifiedBy = userId;
					dbRSC.Save(rsc);

					dataRetVal.Add(entity);

					// create ShopFloorQAPar records
					foreach(var qaPar in qaPars)
					{
						var sfQAPar = new ShopFloorQAPar();
						sfQAPar.CreatedBy = userId;
						sfQAPar.CreatedOn = d;
						sfQAPar.QAParamID = qaPar.QAParamID;
						sfQAPar.ShopFloorID = newShopFloorId;
						sfQAPar.QAParamActual = qaPar.QAParam.QAParaValueNum;
						db.CreateShopFloorQAParam(sfQAPar);
					}
				}
			}

			return Json(dataRetVal, JsonRequestBehavior.AllowGet);
		}

		[HttpPost]
		public JsonResult StopResource(int[] shopFloorIDs)
		{
			DateTime dateEnd = DateTime.Now;
			DateTime dateStart = dateEnd;
			var userId = db.GetUserIDByUsername(User.Identity.Name);

			var dbRSC = new MODetailRSCManager();
			var dbSched = new MOResourceScheduleManager();

			// get elapsed time.
			TimeSpan ts = new TimeSpan();

			foreach (var id in shopFloorIDs)
			{
				var sf = db.GetByID(id);
				sf.ModifiedBy = userId;
				sf.ModifiedOn = dateEnd;
				sf.EndDate = dateEnd;

				dateStart = sf.StartDate.Value;
				ts = (dateEnd - dateStart);
				sf.Duration = (decimal) ts.TotalHours;

				db.Save(sf);

                // set OnStreamTag to 0
                var rsc = db.GetMODetailRSC(sf.MODetailRSCID);
                if (rsc != null)
                {
                    rsc.OnStreamTag = false;
                    rsc.ModifiedBy = userId;
                    rsc.ModifiedOn = dateEnd;
                    dbRSC.Save(rsc);
                }

				dbSched.DeleteSchedByFGGID(sf.MODetailRSCID);
			}



			

			var jsonData = new
			{
				ElapsedTime = ts.ToString(@"hh\:mm\:ss"),
				EndDate = dateEnd,
				StartDate = dateStart
			};

			return Json(jsonData, JsonRequestBehavior.AllowGet);
		}

		private void ArchiveRSC(MODetailRsc rsc)
		{
            var dbFGG = new MODetailFGGManager();
            var fgg = dbFGG.GetByIDIncluding(rsc.MODetailFGGID, m => m.MOHeader, m1 => m1.MOHeader.MOType);
            var mo = fgg.MOHeader;
			var hsRSC = new HSMODetailRsc();
			hsRSC.MOType = mo.MOType.MOTypeCode;
			hsRSC.MONumber = mo.MONumber;
			hsRSC.FGItemCode = fgg.ItemCode;
			hsRSC.ResourceCode = rsc.ResourceCode;
			hsRSC.SetupTime = rsc.SetupTime;
			hsRSC.StockTime = rsc.StockTime;
			hsRSC.EstTime = rsc.EstTime;
			hsRSC.FromDate = rsc.FromDate;
			hsRSC.ToDate = rsc.ToDate;
			hsRSC.OrigFromDate = rsc.OrigFromDate;
			hsRSC.OrigToDate = rsc.OrigToDate;
			hsRSC.OrigEstTime = rsc.OrigEstTime;
            hsRSC.RSCSeq = rsc.ID; // as per client request. store MODetailRSCID instead of rsc.Sequence; also see ManufacturingOrderController.Archive()
            hsRSC.ClosedTag = (short)(rsc.ClosedTag.GetValueOrDefault(false) ? 1 : 0);
			hsRSC.OnStreamTag = (short)(rsc.OnStreamTag.GetValueOrDefault(false) ? 1 : 0);
			hsRSC.MOStat = (short)(rsc.OnHold.GetValueOrDefault(false) ? 0 : 1);
			hsRSC.MOPriority = mo.MOPriority;
			hsRSC.PriorityTag = (short)(rsc.PriorityTag.GetValueOrDefault(false) ? 1 : 0);
			hsRSC.BatchPrcnt = (short)rsc.BatchPercent.GetValueOrDefault(0);
			//db.HSMODetailRscs.Add(hsRSC);
			var dbHSMO = new ShopFloorEntityManager<HSMODetailRsc>(m => m.ID);
			dbHSMO.Create(hsRSC);
		}

		[HttpPost]
		public JsonResult CloseResource(int[] shopFloorIDs)
		{
			{
				DateTime dateNow = DateTime.Now;
				var userId = db.GetUserIDByUsername(User.Identity.Name);

				var dbRsc = new MODetailRSCManager();

				foreach (var id in shopFloorIDs)
				{
					var sf = db.GetByID(id);
					sf.ModifiedBy = userId;
					sf.ModifiedOn = dateNow;

					db.Save(sf);

                    var rsc = db.GetMODetailRSC(sf.MODetailRSCID);
                    if (rsc != null)

ShopFloor.Web/Views/DataCapture/List.cshtml
@{
	ViewBag.Title = "List";
}


<h2>Work In Process</h2>

<div class="row">
	<div class="col-md-7 col-sm-12 col-xs-12">
		<div class="input-group">
			<input type="text" class="form-control txt-table-search" placeholder="Enter Work in Process Details" name="SearchString" autofocus>
			<span class="input-group-btn">
				<button type="submit" class="btn btn-primary btn-search btn-table-search"><span class="glyphicon glyphicon-search"></span></button>
			</span>
		</div>
	</div>
	<div class="col-md-5 col-sm-12 col-xs-12">

		<a href='@Url.Action("Index", "ManufacturingOrder")' class="btn btn-success pull-right"><span class="glyphicon glyphicon-plus"></span>&nbsp;Create New</a>

	</div>
</div>

<table id="tblList" class="table">
	<thead>
		<tr>
			<th>WIP ID</th>
			<th>Resource</th>
			<th>Activity</th>
			<th>Start</th>
			<th>End</th>
			<th>Status</th>
			<th>User</th>
		</tr>
	</thead>
</table>




@section Scripts{
	<link href="~/Content/dataTables.bootstrap.css" rel="stylesheet" />
	<script src="~/Scripts/jquery.dataTables.min.js"></script>
	<script src="~/Scripts/dataTables.bootstrap.js"></script>
	<script src="~/Scripts/shopfloor.datatable.js"></script>
	<script>
        var tblSearch = {};
        $(function () {
            tblSearch = new SearchTable('@ShopFloor.Constants.CONST_SEARCHTABLE_DATACAPTURE', '#tblList', '.txt-table-search', '.btn-table-search', btnSelectRow_Click, undefined, undefined);
            tblSearch.AjaxURL = '@Response.ApplyAppPathModifier(ShopFloor.Constants.CONST_SEARCHTABLE_URL)' + '@ShopFloor.Constants.CONST_SEARCHTABLE_DATACAPTURE';
            tblSearch.addDataTableColumn('ID', false, false, true);
            tblSearch.addDataTableColumn('ResourceCode', true, true);
            tblSearch.addDataTableColumn('ActivityType.ActivityCode', true, true);
            tblSearch.addDataTableColumn('DisplayStartDate', true, true);
            tblSearch.addDataTableColumn('DisplayEndDate', true, true);
            tblSearch.addDataTableColumn('Status', true, true);
            tblSearch.addDataTableColumn('Username', true, true);
            tblSearch.showActionButtons = false
            tblSearch.showSelectButton = true;
            tblSearch.initialize();
        });

        var btnSelectRow_Click = function (id) {
            location.href = '@Response.ApplyAppPathModifier("/DataCapture/Edit/")' + id
        }

	</script>
}

ShopFloor.Web/Views/DataCapture/_EditDataCapturePartial.cshtml
@model EditDataCaptureModel

<div class="row">

    <div class="col-md-12">

        <form id="form-datacapture-@Model.DataCaptureID" class="form-datacapture">

            @Html.HiddenFor(m => m.DataCaptureID)
            @Html.HiddenFor(m => m.StartDateTime)
            @Html.HiddenFor(m => m.ElapsedTime)
            @Html.HiddenFor(m => m.EndDateTime)
            @Html.HiddenFor(m => m.IsStarted)
            @Html.HiddenFor(m => m.MODetailRSCID)
            
            <div class="tab-content">


                @Html.ValidationSummary(false)
                <div class="validation-summary-errors custom-validation-summary text-center bolder">
                    <div class="well well-sm danger">
                        There are some fields that require your attention
                    </div>
                </div>

                <div role="tabpanel" class="tab-pane active container" id="tabGeneralInfo-@Model.DataCaptureID">

                    <div class="form-horizontal">

                        <div class="form-group">
                            <label class="control-label col-md-3">Start Time</label>
                            <div class="col-md-9">
                                @if (Model.IsCaptured)
                                {
                                    <p id='p-starttime-@Model.DataCaptureID' class="form-control-static bolder">@Model.StartDateTime.ToString("MM/dd/yyyy HH:mm:ss tt")</p>
                                }
                                else if(Model.IsStarted)
                                {
                                    <p id='p-starttime-@Model.DataCaptureID' class="form-control-static bolder">@Model.StartDateTime.ToString("MM/dd/yyyy HH:mm:ss tt")</p>
                                }
                                else
                                {
                                    <p id='p-starttime-@Model.DataCaptureID' class="form-control-static timer-start">@Model.StartDateTime.ToString("MM/dd/yyyy HH:mm:ss tt")</p>
                                }
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label col-md-3">Elapsed Time</label>
                            <div class="col-md-9">
                            @if (Model.IsCaptured)
                            {
                                <p id='p-elapsedtime-@Model.DataCaptureID' class="form-control-static bolder">@Model.ElapsedTime.ToString(@"hh\:mm\:ss")</p>
                            }
                            else
                            {
                                <p id='p-elapsedtime-@Model.DataCaptureID' class="form-control-static timer-elapsed">--:--:--</p>
                            }

                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label col-md-3">Stop Time</label>
                            <div class="col-md-9">
                                @if (Model.IsCaptured)
                                {
                                    <p id='p-stoptime-@Model.DataCaptureID' class="form-control-static bolder">@Model.EndDateTime.ToString("MM/dd/yyyy HH:mm:ss tt")</p>
                                }
                                else if (Model.IsStarted)
                                {
                                    <p id='p-stoptime-@Model.DataCaptureID' class="form-control-static timer-stop">@Model.EndDateTime.ToString("MM/dd/yyyy HH:mm:ss tt")</p>
                                }
                                else
                                {
                                    <p id='p-stoptime-@Model.DataCaptureID' class="form-control-static">--/--/---- --:--:-- --</p>
                                }

                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-9 col-md-offset-3">
                                @if (Model.IsCaptured)
                                {
                                    <button data-id="@Model.DataCaptureID" type="button" class="btn btn-warning btn-captured not-implemented"><i class="glyphicon glyphicon-thumbs-up"></i> Close</button>
                                }
                                else if (Model.IsStarted)
                                {
                                    <button data-id="@Model.DataCaptureID" type="button" class="btn btn-danger btn-stop"><i class="glyphicon glyphicon-stop"></i> Stop</button>
                                }
                                else
                                {
                                    <button data-id="@Model.DataCaptureID" type="button" class="btn btn-default btn-start"><i class="glyphicon glyphicon-play"></i> Start</button>
                                }
                            </div>
                        </div>

                    </div>

                </div>

                <div role="tabpanel" class="tab-pane container" id="tabResources-@Model.DataCaptureID">

                    <div class="col-md-8">

                        <div class="form-horizontal">

                            <div class="form-group">
                                <label class="control-label col-md-4" for="ActivityID">Activity</label>
                                <div class="col-md-8">
                                    @Html.DropDownListFor(m => m.ActivityTypeID, (IEnumerable<SelectListItem>)ViewBag.Activities, "", new { @class = "form-control", required = "required" })
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="control-label col-md-4" for="SubstituteResource">Substitute?</label>
                                <div class="col-md-8">
                                    <div class="checkbox">
                                        @Html.CheckBoxFor(m => m.SubstituteResource)
                                    </div>
                                </div>
                            </div>

                            <div class="form-group disable">
                                <label class="control-label col-md-4" for="SubstituteResourceID">Substitute Resource</label>
                                <div class="col-md-8">
                                    <select id="SubstituteResourceID" class="form-control">
                                        <option>choose a substitute resource</option>
                                    </select>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>

                <div role="tabpanel" class="tab-pane container" id="tabAddRM-@Model.DataCaptureID">

                    <div class="col-md-8">
                        <div class="form-horizontal">

                            <div class="form-group">
                                <label for="ResourceID" class="control-label col-md-4">Additional RM</label>
                                <div class="col-md-8">
                                    @Html.DropDownListFor(m => m.RMItemCode, (IEnumerable<SelectListItem>)ViewBag.RMAddlItems, "", new { @class = "form-control" })
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="control-label col-md-4" for="SubstituteResourceID">Reason</label>
                                <div class="col-md-8">
                                    @Html.DropDownListFor(m => m.AddlReasonID, (IEnumerable<SelectListItem>)ViewBag.AddddlReasons, "", new { @class = "form-control" })
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="control-label col-md-4" for="ActivityID">RM Quantity</label>
                                <div class="col-md-8">
                                    @Html.TextBoxFor(m => m.RMQuantity, new { @class = "form-control", type = "number" })
                                </div>
                            </div>

                        </div>
                    </div>

                </div>

                <div role="tabpanel" class="tab-pane container" id="tabOthers-@Model.DataCaptureID">

                    <div class="col-md-8">
                        <div class="form-horizontal">

                            <div class="form-group">
                                <label for="ResourceID" class="control-label col-md-5">Good</label>
                                <div class="col-md-7">
                                    @Html.TextBoxFor(m => m.Good, new { @class = "form-control", type = "number" })
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="control-label col-md-5" for="SubstituteResourceID">Run Rate Reason</label>
                                <div class="col-md-7">
                                    @Html.DropDownListFor(m => m.RunRateReasonID, (IEnumerable<SelectListItem>)ViewBag.RunRateReasons, "", new { @class = "form-control" })
                                </div>
                            </div>


                        </div>
                    </div>


                </div>

                <div role="tabpanel" class="tab-pane container" id="tabRejects-@Model.DataCaptureID" ng-controller="">
                    <div class="col-md-8">

                        <table class="table table-condensed">
                            <thead>
                                <tr>
                                    <th>Criteria Code</th>
                                    <th>Reject Quantity</th>
                                    <th></th>
                                </tr>
                                <tr>
                                    <th><select class="form-control"><option>choose a criteria</option></select></th>
                                    <th><input type="text" class="form-control" /></th>
                                    <th><button class="btn btn-success btn-sm"><i class="glyphicon glyphicon-plus"></i> Add Reject</button></th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td>CC 1</td>
                                    <td>100</td>
                                    <td></td>
                                </tr>
                                <tr>
                                    <td>CC 2</td>
                                    <td>200</td>
                                    <td></td>
                                </tr>
                                <tr>
                                    <td>CC 3</td>
                                    <td>300</td>
                                    <td></td>
                                </tr>
                            </tbody>
                        </table>

                    </div>
                </div>

                <div class="capture-item-action-buttons">
                    <a class="text-muted btn-action-item-cancel" href="#" data-id="@Model.DataCaptureID">Cancel</a> |
                    <a class="text-muted btn-action-item-save" href="#" data-id="@Model.DataCaptureID">Save</a> |
                    <a class="text-muted btn-action-item-close" href="#">Close Resource</a>
                </div>

            </div> @*tab-content*@

        </form>
    </div>

</div> 

ShopFloor.Web/Views/DataCapture/_QAParameterEntry.cshtml
<div class="panel panel-default">
	<div class="panel-heading">QA Parameters Entry</div>
	<table class="table table-striped">
		<thead>
			<tr>
				<th class="col-xs-3">Parameter Code</th>
				<th class="col-xs-3">Parameter Description</th>
				<th class="col-xs-2">Parameter 1</th>
				<th class="col-xs-2">Parameter 2</th>
				<th class="col-xs-3">Actual</th>
				<th class="col-xs-1"></th>
			</tr>
		</thead>
		<tbody>
			<tr ng-repeat="item in fggCtrl.gridQAParams">
				<td>{{item.QAParam.QAParaCode}}</td>
				<td>{{item.QAParam.QAParaDesc}}</td>
				<td>{{item.QAParam.QAParaValueNum}}</td>
				<td>{{item.QAParam.QAParaValueNum2}}</td>
				<td><input ng-model="item.QAParaValueNum" type='number' class="form-control" ng-change="item.changed=true" ng-disabled="fggCtrl.status<1" value="{{item.QAParam.QAParaValueNum}}" /></td>
				<td><button class="btn btn-sm btn-primary" ng-disabled="!item.changed" ng-click="item.changed=false;fggCtrl.saveQAParam(item);"><i class="fa fa-floppy-o"></i></button></td>
			</tr>
			<tr ng-show="fggCtrl.gridQAParams.length==0">
				<td colspan="4">
					There are no records found.
				</td>
			</tr>
		</tbody>
	</table>
</div>

ShopFloor.Web/Views/DataCapture/_Timer.cshtml
@*Timer - begin*@
<div class="row top-buffer-25">
	<div class="col-xs-12">
		<div class="text-center">
			<button class="btn btn-success btn-xl" ng-show="fggCtrl.status==0" ng-click="fggCtrl.startResource($event, fggCtrl.SelectedResourceModel)"><i class="glyphicon glyphicon-play"></i> START</button>
			<button class="btn btn-danger btn-xl" ng-show="fggCtrl.status==1" ng-click="fggCtrl.stopResource($event, fggCtrl.SelectedResourceModel)"><i class="glyphicon glyphicon-stop"></i> STOP</button>
			<button class="btn btn-primary btn-xl" ng-show="fggCtrl.status==2" ng-click="fggCtrl.closeResource($event, fggCtrl.SelectedResourceModel)"><i class="glyphicon glyphicon-folder-close"></i> CLOSE RESOURCE</button>
			<button class="btn btn-default btn-xl" ng-show="fggCtrl.status==3" disabled="disabled"><i class="glyphicon glyphicon-flag"></i> CLOSED</button>
			<p ng-show="fggCtrl.status==3">
				@Html.ActionLink("Create Work in Process", "Index", "DataCapture", new { id = Model.ID })
			</p>
		</div>
	</div>
</div>

<div class="row top-buffer-25">

	@*Schedule Time Start*@
	<div class="col-md-6 col-lg-6">
		<div class="panel panel-default">
			<div class="panel-heading">
				Scheduled
			</div>
			<div class="panel-body">
				<div class="row">
					<div class="col-xs-12 timer-text">
						<label class="col-xs-5 text-right">Start Time</label>
						<div class="col-xs-7">
							<span id="dateStart">{{fggCtrl.ScheduleStartDate}}</span>
						</div>
					</div>
				</div>
				<div class="row">
					<div class="col-xs-12 timer-text">
						<label class="col-xs-5 text-right">Planned Duration</label>
						<div class="col-xs-7">
							<span id="dateElapsed">{{fggCtrl.ScheduleElapsedTime}}</span>
						</div>
					</div>
				</div>
				<div class="row">
					<div class="col-xs-12 timer-text">
						<label class="col-xs-5 text-right">Stop Time</label>
						<div class="col-xs-7">
							<span id="dateStop">{{fggCtrl.ScheduleEndDate}}</span>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	@*Schedule Time End*@



	@*Actual Time Start*@
	<div class="col-md-6 col-lg-6">
		<div class="panel panel-primary">
			<div class="panel-heading">
				<i class="fa fa-exclamation-circle"></i> Actual
			</div>
			<div class="panel-body">
				<div class="row">
					<div class="col-xs-12 timer-text">
						<label class="col-xs-5 text-right">Start Time</label>
						<div class="col-xs-7">
							<span id="dateStart">{{fggCtrl.timeStart}}</span>
						</div>
					</div>
				</div>
				<div class="row">
					<div class="col-xs-12 timer-text">
						<label class="col-xs-5 text-right">Elapsed Time</label>
						<div class="col-xs-7">
							<span id="dateElapsed">{{fggCtrl.timeElapsed}}</span>
						</div>
					</div>
				</div>
				<div class="row">
					<div class="col-xs-12 timer-text">
						<label class="col-xs-5 text-right">Stop Time</label>
						<div class="col-xs-7">
							<span id="dateStop">{{fggCtrl.timeStop}}</span>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	@*Actual Time End*@
</div>
@*Timer - end*@