ShopFloor.Web/Controllers/OperationsController.cs
using ShopFloor.Entities;
using ShopFloor.Managers;
using System;
using System.Net;
using System.Web.Mvc;

namespace ShopFloor.Web.Controllers
{
    [Authorize]
    public class OperationsController : BaseController
    {
        private ShopFloorEntityManager<Operation> db = new ShopFloorEntityManager<Operation>(m => m.ID);

        // GET: Operations
        public ActionResult Index()
        {
            return View(db.GetAll());
        }

        public ActionResult Create()
        {
            return View(new Operation { Active = true });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Operation operation)
        {
            if (ModelState.IsValid)
            {
                if (!db.IsDuplicate(m => m.OperCode == operation.OperCode))
                {
                    operation.CreatedBy = db.GetUserIDByUsername(User.Identity.Name);
                    operation.CreatedOn = DateTime.Now;
                    operation.Sequence = db.GetNextSequence(m => m.Sequence);
                    db.Create(operation);
                    AddMessageSuccess("Record successfully created.");
                    return RedirectToAction("Index");
                }
                ModelState.AddModelError("OperCode", "Duplicate Operation Code found.");
            }
            return View(operation);
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Operation operation = db.GetByID(id.Value);
            if (operation == null)
            {
                return HttpNotFound();
            }

            return View(operation);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Operation operation)
        {
            if (ModelState.IsValid)
            {
                if (!db.IsDuplicate(m => m.OperCode == operation.OperCode && m.ID != operation.ID))
                {
                    operation.ModifiedBy = db.GetUserIDByUsername(User.Identity.Name);
                    operation.ModifiedOn = DateTime.Now;
                    db.Save(operation);
                    AddMessageSuccess("Record saved.");
                    return RedirectToAction("Index");
                }

                ModelState.AddModelError("OperCode", "Duplicate Operation Code found.");

            }
            return View(operation);
        }

        public JsonResult Delete(int id)
        {
            db.Remove(id);
            return Json(true, JsonRequestBehavior.AllowGet);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ShopFloor.Web/Controllers/RoutesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ShopFloor.Entities;
using ShopFloor.Web.Models;
using ShopFloor.Managers;
using ShopFloor.SAP.Managers;

namespace ShopFloor.Web.Controllers
{
    [Authorize]
    public class RoutesController : BaseController
    {
        private RoutesManager db = new RoutesManager();

        // GET: Routes
        public ActionResult Index()
        {
            return View();
        }

        // GET: Routes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Route route = db.GetByID(id.Value);
            if (route == null)
            {
                return HttpNotFound();
            }
            return View(route);
        }

        // GET: Routes/Create
        public ActionResult Create()
        {
            var model = new EditRouteModel();
            model.Active = true;
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(EditRouteModel model)
        {
            if (ModelState.IsValid)
            {
                if (!db.IsDuplicate(m => m.RouteCode == model.RouteCode))
                {
                    if (ModelState.IsValid)
                    {
                        model.CreatedOn = DateTime.Now;
                        model.CreatedBy = db.GetUserIDByUsername(User.Identity.Name);
                        db.Create(model);
                        AddMessageSuccess(model.RouteCode + " route has been created.");
                        return RedirectToAction("Index");
                    }

                }
                else
                {
                    ModelState.AddModelError("RouteCode", "A Route with the same RouteCode already exists.");
                }
            }

            return View(model);
        }

        // GET: Routes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Route route = db.GetByID(id.Value);
            if (route == null)
            {
                return HttpNotFound();
            }

            EditRouteModel model = db.Map(route, new EditRouteModel());
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(EditRouteModel model)
        {
            if (ModelState.IsValid)
            {
                if (!db.IsDuplicate(m => m.RouteCode == model.RouteCode && m.ID != model.ID))
                {
                    if (ModelState.IsValid)
                    {
                        model.ModifiedOn = DateTime.Now;
                        model.ModifiedBy = db.GetUserIDByUsername(User.Identity.Name);
                        db.Save(model);
                        AddMessageSuccess(model.RouteCode + " route has been updated.");
                        return RedirectToAction("Index");
                    }
                }
                else
                {
                    ModelState.AddModelError("RouteCode", "A Route with the same RouteCode already exists.");
                }

            }

            return View(model);
        }

        // GET: Routes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            db.Remove(id.Value);
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult AssociateOperation(int id)
        {
            var mgr = new RoutesManager();
            var opmgr = new ShopFloorEntityManager<Operation>(m => m.ID);
            var route = mgr.GetByID(id);

            var model = new EditRouteOperationModel();
            model.RouteID = id;
            model.RouteCode = route.RouteCode;
            model.RouteDesc = route.RouteDesc;
            ViewBag.Operations = opmgr.GetAll();

            return View(model);
        }

        [HttpPost]
        public ActionResult AssociateOperation(EditRouteOperationModel model)
        {
            if (ModelState.IsValid)
            {
                // check for duplicates
                var routeOpMgr = new RouteOperationsManager();
                if (!routeOpMgr.IsDuplicate(m => m.RouteID == model.RouteID || m.OperationID == model.OperationID))
                {
                    // add 
                    routeOpMgr.Create(new RouteOperation { OperationID = model.OperationID, RouteID = model.RouteID });

                    // go back to list
                    return RedirectToAction("Operations", new { id = model.RouteID });
                }

                ModelState.AddModelError("", "This Operation is already associated with this Route.");
            }

            var opmgr = new ShopFloorEntityManager<Operation>(m => m.ID);
            ViewBag.Operations = opmgr.GetAll();

            return View(model);
        }


        public JsonResult GetSAPItemDetails(string itemcode)
        {
            var mgr = new SAP.Managers.SAPItemManager();
            var model = mgr.GetByItemCode(itemcode);
            return Json(model, JsonRequestBehavior.AllowGet);
        }


        public JsonResult GetRouteDetailsByID(int id)
        {
            var entity = db.GetByID(id);
            return Json(entity, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetRouteDetailsByItemCode(string itemCode)
        {
            var entity = db.GetByItemCode(itemCode);
            return Json(entity, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetItemRouteByItemCode(string itemCode)
        {
            var entity = db.GetItemRouteByItemCode(itemCode);
            return Json(entity, JsonRequestBehavior.AllowGet);
        }

        public JsonResult DeleteRoute(int id)
        {
            db.Remove(id);
            return Json(true, JsonRequestBehavior.AllowGet);
        }


        #region RouteOperations
        public JsonResult GetOperations()
        {
            var jsondata = new ShopFloorEntityManager<Operation>(m => m.ID).GetAll();
            return Json(jsondata, JsonRequestBehavior.AllowGet);
        }
        public JsonResult GetRouteOperations(int id)
        {
            var operations = new RouteOperationsManager().GetAllByRouteID(id);
            var jsondata = (from o in operations
                            select new
                            {
                                ID = o.ID,
                                OperationID = o.OperationID,
                                RouteID = o.RouteID,
                                OperCode = o.Operation.OperCode,
                                OperDesc = o.Operation.OperDesc,
                                Sequence = o.Sequence,
                            });
            return Json(jsondata, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public JsonResult AddRouteOperation(RouteOperation operation)
        {
            var newRo = new RouteOperation();
            newRo.CreatedBy = db.GetUserIDByUsername(User.Identity.Name);
            newRo.CreatedOn = DateTime.Now;
            newRo.OperationID = operation.OperationID;
            newRo.RouteID = operation.RouteID;

            var dbRO = new RouteOperationsManager();
            int id = dbRO.Create(newRo);
            var model = dbRO.GetByID(id);

            var jsondata = new
            {
                ID = model.ID,
                RouteID = model.RouteID,
                OperationID = model.OperationID,
                OperCode = model.Operation.OperCode,
                OperDesc = model.Operation.OperDesc,
                Sequence = model.Sequence,
            };

            return Json(jsondata, JsonRequestBehavior.AllowGet);
        }
        public JsonResult DeleteRouteOperation(int routeOperationId)
        {
            var dbRO = new RouteOperationsManager();
            dbRO.Remove(routeOperationId);
            return Json(true, JsonRequestBehavior.AllowGet);
        }
        #endregion

        #region RouteResources
        public JsonResult GetAllResources()
        {
            var dbRes = new ResourceManager();
            return Json(dbRes.GetAll(), JsonRequestBehavior.AllowGet);
        }
        public JsonResult GetRouteResources(int id, int operationId)
        {
            var dbROR = new RouteOperationResourcesManager();
            List<RouteOperationResource> result;
            if (operationId > 0)
                result = dbROR.GetByRouteID(id, operationId);
            else
                result = dbROR.GetByRouteID(id);

            var jsondata = GetJSOnRouteResources(result);

            return Json(jsondata, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult AddRouteResource(RouteOperationResource routeResource)
        {
            var newRecord = new RouteOperationResource();
            newRecord.CreatedBy = db.GetUserIDByUsername(User.Identity.Name);
            newRecord.CreatedOn = DateTime.Now;

            newRecord.Active = true;
            newRecord.ResourceID = routeResource.ResourceID;
            newRecord.RouteOperationID = routeResource.RouteOperationID;

            var dbRO = new RouteOperationResourcesManager();
            int id = dbRO.Create(newRecord);
            var model = dbRO.GetByID(id);

            var jsondata = GetJSONRouteResource(model);

ShopFloor.Web/Views/Routes/AssociateOperation.cshtml
@model ShopFloor.Web.Models.EditRouteOperationModel
@{
    ViewBag.Title = "Add Operation";
    ViewBag.ActiveMenu = "AssociateOperation";
    Layout = "_LayoutRoutesEdit.cshtml";
    ViewBag.RouteID = Model.RouteID;
    ViewBag.RouteCode = Model.RouteCode;
}

<h2>Add @Html.ActionLink(Model.RouteCode, "Edit", "Routes", new { id = Model.RouteID }, null) Operation</h2>
<hr />

<div class="col-lg-8 col-md-9">
    @using (Html.BeginForm("Form1"))
    {
        @Html.AntiForgeryToken()

        @Html.HiddenFor(m => m.RouteID)
        @Html.HiddenFor(m => m.RouteCode)
        @Html.HiddenFor(m => m.RouteDesc)

        <div class="form-horizontal">

            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="form-group">
                @Html.LabelFor(model => model.RouteCode, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <p class="form-control-static">@Html.ActionLink(Model.RouteCode, "Edit", "Routes", new { id = Model.RouteID }, null)</p>
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.RouteDesc, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <p class="form-control-static">@Model.RouteDesc</p>
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.OperationID, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownListFor(m => m.OperationID, new SelectList(ViewBag.Operations, "ID", "OperCode"), "select", new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.OperationID, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <button type="submit" class="btn btn-success"><span class="glyphicon glyphicon-plus"></span>&nbsp;Add Route Operation</button>
                </div>
            </div>
        </div>
    }

    <p>
        @Html.ActionLink("Back to List", "Operations", "Routes", new { id = Model.RouteID }, null)
        | @Html.ActionLink("Add Operation", "Create", "Operations", null, null)
    </p>
</div>

ShopFloor.Web/Views/Routes/Create.cshtml
@model ShopFloor.Web.Models.EditRouteModel

@{
    ViewBag.Title = "Create Route";
    ViewBag.ActiveMenu = "Routes";
    Layout = "_LayoutRoutes.cshtml";
    ViewBag.RouteID = Model.ID;
}

<h2>Route Maintenance</h2>
<h4>New Route</h4>
<hr />

<div class="col-lg-8">
    @using (Html.BeginForm("CreateRoute"))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">

            <div class="form-group">
                @Html.LabelFor(model => model.RouteCode, htmlAttributes: new { @class = "control-label col-md-3" })
                <div class="col-md-9">
                    @Html.EditorFor(model => model.RouteCode, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.RouteCode, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.RouteDesc, htmlAttributes: new { @class = "control-label col-md-3" })
                <div class="col-md-9">
                    @Html.EditorFor(model => model.RouteDesc, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.RouteDesc, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.SBUCode, htmlAttributes: new { @class = "control-label col-md-3" })
                <div class="col-md-9">
                    <select id="SBUCode" name="SBUCode" class="form-control">
                        <option @((Model.SBUCode ?? "") == "" ? "selected" : "")></option>
                        <option @((Model.SBUCode) == "OSBU2" ? "selected" : "")>OSBU2</option>
                        <option @((Model.SBUCode) == "PSBU3" ? "selected" : "")>PSBU3</option>
                        <option @((Model.SBUCode) == "GSBU4" ? "selected" : "")>GSBU4</option>
                        <option @((Model.SBUCode) == "SSBU" ? "selected" : "")>SSBU</option>
                    </select>
                    @Html.ValidationMessageFor(model => model.SBUCode, "", new { @class = "text-danger" })
                </div>
            </div>

			<div class="form-group">
				@Html.LabelFor(model => model.Active, htmlAttributes: new { @class = "control-label col-md-3" })
				<div class="col-md-9">
					<div class="checkbox">
						@Html.EditorFor(model => model.Active)
						@Html.ValidationMessageFor(model => model.Active, "", new { @class = "text-danger" })
					</div>
				</div>
			</div>

			<div class="form-group">
				@Html.LabelFor(model => model.DownTimeTag, htmlAttributes: new { @class = "control-label col-md-3" })
				<div class="col-md-9">
					<div class="checkbox">
						@Html.EditorFor(model => model.DownTimeTag)
						@Html.ValidationMessageFor(model => model.DownTimeTag, "", new { @class = "text-danger" })
					</div>
				</div>
			</div>


            @*@Html.HiddenFor(m => m.ItemName)
            @Html.HiddenFor(m => m.ItemGroupCode)
            @Html.HiddenFor(m => m.ItemGroupName)
            @Html.HiddenFor(m => m.ItemCategory)*@

            <div class="form-group">
                <div class="col-md-offset-3 col-md-9">
                    <button type="submit" class="btn btn-success"><span class="glyphicon glyphicon-plus"></span>&nbsp;Create</button>
                </div>
            </div>
        </div>
    }

    <p>
        @Html.ActionLink("Search Route", "Index")
    </p>
</div>

@Html.Partial("~/Views/Shared/_ItemSearch.cshtml")


    @section Scripts{
        <link href="~/Content/dataTables.bootstrap.css" rel="stylesheet" />
        <script src="~/Scripts/jquery.dataTables.min.js"></script>
        <script src="~/Scripts/dataTables.bootstrap.js"></script>
        @*<script src="~/Scripts/shopfloor-popup-search.js"></script>*@
        <script>

            searchButton_click = function (code, desc) {
                
                $('#ItemCode').val(code);

                $.get('@Response.ApplyAppPathModifier("/Routes/GetSAPItemDetails?itemcode=")' + code, function (data) {
                    //alert(JSON.stringify(data));
                    $('#ItemName').val(data.ItemName);
                    $('#pItemName').html(data.ItemName);

                    $('#ItemGroupCode').val(data.ItmsGrpCod);
                    $('#pItemGroupCode').html(data.ItmsGrpCod);

                    $('#ItemGroupName').val(data.ItmsGrpNam);
                    $('#pItemGroupName').html(data.ItmsGrpNam);

                    $('#ItemCategory').val(data.U_ITEMCAT01);
                    $('#pItemCategory').html(data.U_ITEMCAT01);

                    toastr['info'](code + ' information copied and stored.');
                });
            }

        </script>
    }

ShopFloor.Web/Views/Routes/Delete.cshtml
@model ShopFloor.Entities.Route

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_LeftPane.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Route</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.RouteCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RouteCode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RouteDesc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RouteDesc)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Active)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Active)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SBUCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SBUCode)
        </dd>

    </dl>

    @using (Html.BeginForm("Form1")) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ShopFloor.Web/Views/Routes/Details.cshtml
@model ShopFloor.Entities.Route

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_LeftPane.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Route</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.RouteCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RouteCode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RouteDesc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RouteDesc)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Active)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Active)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SBUCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SBUCode)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

ShopFloor.Web/Views/Routes/Index.cshtml
@model ShopFloor.Entities.Route

@{
    ViewBag.Title = "Routes";
    ViewBag.ActiveMenu = "Routes";
    Layout = "_LayoutRoutesIndex.cshtml";
}

<h2>Search Routes</h2>

<div class="row">
    <div class="col-md-7 col-sm-7 col-xs-7">
        <div class="input-group">
			<input type="text" class="form-control txt-table-search" placeholder="search" name="SearchString">
            <span class="input-group-btn">
                <button type="submit" class="btn btn-primary btn-search btn-table-search"><span class="glyphicon glyphicon-search"></span></button>
            </span>
        </div>
    </div>
    <div class="col-md-5 col-sm-5 col-xs-5">
        <a href="@Url.Action("Create")" class="btn btn-success pull-right"><span class="glyphicon glyphicon-plus"></span>&nbsp;Create New</a>
    </div>
</div>
<table class="table table-striped table-hover table-search" id="table-search-route">
	<thead>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.RouteCode)
        </th>
        <th class="hidden-xs__">
            @Html.DisplayNameFor(model => model.RouteDesc)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Active)
        </th>
        <th></th>
    </tr>
	</thead>
	<tbody>
	</tbody>

</table>



@section Scripts{
<link href="~/Content/dataTables.bootstrap.css" rel="stylesheet" />
<script src="~/Scripts/jquery.dataTables.min.js"></script>
<script src="~/Scripts/dataTables.bootstrap.js"></script>
<script src="~/Scripts/shopfloor.datatable.js"></script>
    <script>

        var tableRoute = {};

        $(function () {
            tableRoute = new SearchTable('@ShopFloor.Constants.CONST_SEARCHTABLE_ROUTE', '.table-search', '.txt-table-search', '.btn-table-search', undefined, btnEditRow_Click, btnDeleteRow_Click);
            tableRoute.AjaxURL = '@Response.ApplyAppPathModifier(ShopFloor.Constants.CONST_SEARCHTABLE_URL)' + '@ShopFloor.Constants.CONST_SEARCHTABLE_ROUTE';
            tableRoute.addDataTableColumn('RouteCode', true, true);
            tableRoute.addDataTableColumn('RouteDesc', true, true);
            //tableRoute.addDataTableColumn('ItemCode', true, true);
            tableRoute.addDataTableColumn('Active', true, false);
            tableRoute.showActionButtons = true;
            tableRoute.showSelectButton = false;
            tableRoute.initialize();
        });


        var btnDeleteRow_Click = function (id) {
            $.get('@Response.ApplyAppPathModifier("/routes/deleteroute/")' + id, function () {
                tableRoute.reload();
                toastr['success']('Record deleted.');
            }, 'json')
            .fail(function (data) {
                toastr['error']('Route is in use. Unable to delete.');
            });
        }

        var btnEditRow_Click = function (id) {
            location.href = '@Response.ApplyAppPathModifier("/Routes/Edit/")' + id
        }

    </script>


}

ShopFloor.Web/Views/Routes/Operations.cshtml
@model ShopFloor.Web.Models.ListOperationModel
@{
    ViewBag.Title = "Operations";
    ViewBag.ActiveMenu = "RouteOperations";
    Layout = "_LayoutRoutesEdit.cshtml";
    ViewBag.RouteID = Model.RouteID;
    ViewBag.RouteCode = Model.RouteCode;
}



<div class="row">
    <div class="col-md-7 col-sm-7 col-xs-7">
        <h2>@Html.ActionLink(Model.RouteCode, "Edit", new { id = Model.RouteID }) Operations</h2>
    </div>
    <div class="col-md-5 col-sm-5 col-xs-5">
        <h2>
            <a href="@Url.Action("AssociateOperation", new { id=Model.RouteID })" class="btn btn-success pull-right"><span class="glyphicon glyphicon-plus"></span>&nbsp;Add Route Operation</a>
        </h2>
    </div>
</div>
<hr />
<div class="row">
    <div class="col-lg-12 col-md-12 col-sm-12">
        <table class="table table-striped table-hover table-search">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(m=>m.Self.OperCode)
                    </th>
                    <th class="hidden-xs">
                        @Html.DisplayNameFor(m=>m.Self.OperDesc)
                    </th>
                    <th>
                        @Html.DisplayNameFor(m=>m.Self.Sequence)
                    </th>
                    <th>
                        @Html.DisplayNameFor(m=>m.Self.Active)
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
            </tbody>

        </table>

        @Html.Partial("_PagerPartial", Model)

        <p>
            @Html.ActionLink("View ALL RouteOperations", "Index", "RouteOperations")
        </p>
    </div>
</div>

@section Scripts{
    <link href="~/Content/dataTables.bootstrap.css" rel="stylesheet" />
    <script src="~/Scripts/jquery.dataTables.min.js"></script>
    <script src="~/Scripts/dataTables.bootstrap.js"></script>
    <script src="~/Scripts/shopfloor.datatable.js"></script>
    <script>
        $(function () {

            var table = new SearchTable('@ShopFloor.Constants.CONST_SEARCHTABLE_ROUTE', '.table-search', '.txt-table-search', '.btn-table-search', undefined, undefined, undefined);
            table.addDataTableColumn('OperCode', true, true);
            table.addDataTableColumn('OperDesc', true, true);
            table.addDataTableColumn('Sequence', true, false);
            table.addDataTableColumn('Active', true, false);
            table.showActionButtons = true;
            table.showSelectButton = false;
            table.initialize();

            $('.btn-delete-row').click(function () {
                if (confirm('are you sure you want to delete this record?')) {
                    var url = '@Url.Action("Delete", new { id = "[recordid]" })';
                    url = url.replace('[recordid]', $(this).data('id'));

                    $.get(url, function () {
                        alert('Record successfully delete!');
                        location.reload();
                    });
                }
                return false;
            });


        });
    </script>
}

ShopFloor.Web/Views/Routes/_LayoutRoutesIndex.cshtml
@{
    Layout = "_LayoutRoutes.cshtml";
}


@section LeftPane
{
<div class="list-group">
    @Html.ListGroupItem("Route Operations", "Index", "RouteOperations", "RouteOperations")
    @Html.ListGroupItem("Routing Maintenance", "Index", "RouteOperationResources", "RouteOperationResources")
</div>

@RenderSection("LeftPane", false)
}


@RenderBody()


@section Scripts{
    @RenderSection("Scripts", false)
}